global: &global
  adapter: postgresql
  pool: 5
  timeout: 5000
  min_messages: warning
  encoding: utf8

development:
  database: portfoliosite_development
  <<: *global

test: &test
  database: portfoliosite_test<%=ENV['TEST_ENV_NUMBER']%>
  <<: *global

production:
  database: portfoliosite_production
  <<: *global
